insert into `EXCHANGE_RATE` (ID_EXCH_RATE, CURRENCY, RATE, DATE) values (1, 'USD', 0.27609867, CURRENT_TIMESTAMP());
insert into `EXCHANGE_RATE` (ID_EXCH_RATE, CURRENCY, RATE, DATE) values (2, 'EUR', 0.23437725, CURRENT_TIMESTAMP());
insert into `EXCHANGE_RATE` (ID_EXCH_RATE, CURRENCY, RATE, DATE) values (3, 'MXN', 5.63616415, CURRENT_TIMESTAMP());