drop table `EXCHANGE_RATE` if exists;
create table `EXCHANGE_RATE` (
ID_EXCH_RATE int generated by default as identity, 
CURRENCY varchar(5),
RATE decimal,
DATE timestamp, 
primary key (ID_EXCH_RATE));